### ISSUE TITLE
[Feature Request] Use patterns to select scoped folders and excluded folders

### ISSUE THREAD

**Issue by QuarticCat** [bartosz-dude/folder-scopes#1]
I want to focus on multiple folders and exclude some sub-folders from them. If we can use IntelliJ style patterns, that will be very flexible and helpful.

**Comment by bartosz-dude** [comment]
Sadly scoping multiple folders in a single scope (in a single root workspace, in multi-root workspace each root gets one folder scope) is not really possible in vs code. Vs code only allows to exclude files from showing up in explorer and it uses a quite limited glob pattern ([official docs](https://code.visualstudio.com/docs/editor/glob-patterns)). I achieve scoping by excluding everything except the target and doing so for two targets it will make both of them hidden.

But from how I understand what you want, this can be achieved with hiding files and folders, which already can be done with this extension.

For example I have a folder structure where I scope to `webapp` and hide every subfolder except `app` and `components` and hide `ui` subfolder of `components` (you can hide subfolders of any depth).

![Screenshot_20240922_143636](https://github.com/user-attachments/assets/7f27fd95-4dc5-40ef-9561-73a33da930fd)

This is done with

![Screenshot_20240922_143733](https://github.com/user-attachments/assets/0a9c0d7c-a54a-44a4-819a-724670ca96a8)

Also vs code [glob patterns](https://code.visualstudio.com/docs/editor/glob-patterns#_glob-pattern-syntax) are supported in `excludePaths`. Just need to make sure the beginning matches the `scopedFolderPath`.

![image](https://github.com/user-attachments/assets/6d62ffdd-2445-41e9-9470-869dc92c776f)

I think making the `Hide File` and `Hide Folder` work on multiple selected files and folders instead of only the last one should make it much easier to get what you want. It's not exactly what you are requesting, but sadly I am limited by vs code on this. Unless I just don't know some trick to make it work.

**Comment by QuarticCat** [comment]
I just created a minimum extension to implement my thoughts. It has only ~100 LOC right now.

https://marketplace.visualstudio.com/items?itemName=QuarticCat.scope-focus
